# Generated by Django 3.0.6 on 2020-05-06 13:54
# Edited by honzie to backfill lat and long

from django.db import migrations, models
from uszipcode import SearchEngine


def get_lat_long(apps, schema_editor):
    Places = apps.get_model('webmanager', 'Place')
    search = SearchEngine(simple_zipcode=True)
    for place in Places.objects.all():
        zipcode = search.by_zipcode(place.zip_code)
        place.lng = zipcode.lng
        place.lat = zipcode.lat
        place.save(update_fields=['lat', 'lng'])


class Migration(migrations.Migration):

    dependencies = [
        ('webmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='lat',
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='lng',
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True),
        ),
        migrations.RunPython(get_lat_long, reverse_code=migrations.RunPython.noop),
    ]
