# Generated by Django 3.0.6 on 2020-08-10 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webmanager', '0003_auto_20200506_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connected_place', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('covid_status', models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('Positive', 'Positive'), ('Negative', 'Negative')], max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='place',
            old_name='house_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=1024, unique=True),
        ),
        migrations.DeleteModel(
            name='UserConnection',
        ),
        migrations.AddField(
            model_name='person',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webmanager.Place'),
        ),
        migrations.AddField(
            model_name='connectedplace',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webmanager.Place'),
        ),
    ]
