# Generated by Django 3.0.6 on 2020-08-13 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmanager', '0004_auto_20200810_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='covid_status',
        ),
    ]
