# Generated by Django 3.1 on 2020-08-23 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webmanager', '0006_auto_20200822_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webmanager.place'),
        ),
    ]
