# Generated by Django 3.1 on 2020-08-23 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webmanager', '0007_auto_20200823_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='created_by',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
