# Generated by Django 3.1 on 2020-09-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmanager', '0009_place_member_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectedplace',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
