# Generated by Django 3.1 on 2020-10-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmanager', '0011_auto_20200929_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectedplace',
            name='verified_delete',
            field=models.BooleanField(default=False),
        ),
    ]
