# Generated by Django 3.1 on 2020-10-03 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webmanager', '0012_connectedplace_verified_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectedplace',
            old_name='verified_delete',
            new_name='delete_requested',
        ),
        migrations.AlterField(
            model_name='person',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webmanager.place'),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(help_text='To delete this Person go to User admin', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
